### ISSUE TITLE
Include bqn-mode on MELPA database

### ISSUE THREAD

**Issue by AndersonTorres** [museoa/bqn-mode#1]
We need to study and implement the procedures needed to include this package in the [MELPA database](https://melpa.org/#/)

Co-related issue on Melpa repo:

https://github.com/melpa/melpa/pull/8239

**Comment by larstvei** [comment]
Hi! Do you want me to go ahead and submit the package to melpa? It might be a good idea to add a README first, and possibly some default keybindings for the major-mode.

**Comment by AndersonTorres** [comment]
Hi! Please do it.

I was thinking in using a README similar to the one in [GNU APL mode](https://github.com/lokedhs/gnu-apl-mode/blob/master/README.md), however in Org Mode instead of Markdown.

**Comment by phikal** [comment]
On this topic, would you like the package to be added to NonGNU ELPA (or even GNU ELPA)?

**Comment by AndersonTorres** [comment]
Is there any relevant difference? As far as I remember gnu elpa is a bit harder to insert.

**Comment by phikal** [comment]
I am not sure what you mean by "insert", but GNU ELPA and NonGNU ELPA
are enabled by default and release stable packages by default.  That
makes it easier for people like me, who don't use MELPA, to install the
package.

**Comment by AndersonTorres** [comment]
As far as I remember, the rules for inclusion on GNU ELPA are stricter than Melpa.

Besides this, I have no further objections.

**Comment by phikal** [comment]
Anderson Torres ***@***.***> writes:

> As far as I remember, the rules for inclusion on GNU ELPA are stricter than Melpa.

GNU ELPA requires all significant contributors to have signed the FSF
copyright assignment, because all packages in GNU ELPA are part of
Emacs.

NonGNU ELPA doesn't have this restriction.  That is also where you will
find `gnu-apl-mode'.  As to my understanding `bqn-mode' is based on the
latter, adding the package to NonGNU ELPA will be easier.

The NonGNU ELPA README[0] also explains the rules for inclusion, but as
far as I see these are all given.  The main one is that

   The package must deliver its full functionality and convenience on a
   completely free platform based on the GNU operating system (in
   practice, GNU/Linux), working exclusively with other free software.

But given that BQN is free software, this is a non-issue.

[0] https://git.savannah.gnu.org/cgit/emacs/nongnu.git/plain/README.org

> Besides this, I have no further objections.

I can take care of everything and send you any patches in case anything
requires fixing on your end.

**Comment by AndersonTorres** [comment]
@phikal please do it.

**Comment by phikal** [comment]
Anderson Torres ***@***.***> writes:

> @phikal please do it.

OK, but there are a few janitorial changes I'd like to propose before
adding it.  Would you be fine with me sending you a diff of suggestions
that you can pick and choose to apply?

**Comment by AndersonTorres** [comment]
Fine to me. If there is no serious problem, you can use the typical pull request interface of github.

**Comment by phikal** [comment]
Anderson Torres ***@***.***> writes:

> Fine to me. If there is no serious problem, you can use the typical
> pull request interface of github.

It is not serious, but it will take me considerably longer to prepare
the patches in that form.

**Comment by AndersonTorres** [comment]
Yes, many people feel uncomfortable with using github.

Indeed I would like something like oldschool mail-list-like "send your patch and we can discuss it".

 However I have no idea how to implement it in a compatible way with github.

**Comment by phikal** [comment]
Anderson Torres ***@***.***> writes:

> Yes, many people feel uncomfortable with using github.

For the record, I could also propose the changes as PRs, it just takes a
lot longer because the web interface is inconvenient.

> Indeed I would like something like oldschool mail-list-like "send your patch and we can discuss it".
>
>  However I have no idea how to implement it.

Have you considered SourceHut?

**Comment by svmhdvn** [comment]
I've added some changes here https://github.com/museoa/bqn-mode/pull/17 to address some of the concerns from https://github.com/melpa/melpa/pull/8239#issuecomment-1295922381. Hopefully this should be all we need to get this in MELPA.

**Comment by svmhdvn** [comment]
Committed in https://github.com/melpa/melpa/commit/17711a1d747932e9be1ccd1d0a3adb64fa6cf1ef. This issue can be closed as fixed now.

**Comment by AndersonTorres** [comment]
Many thanks, guys!

Next step: update Nixpkgs!
